# Generated by Django 4.1.2 on 2022-11-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administrator', models.AutoField(primary_key=True, serialize=False, verbose_name='管理员')),
                ('administrator_name', models.CharField(max_length=64, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.AutoField(primary_key=True, serialize=False, verbose_name='班级ID')),
                ('class_name', models.CharField(max_length=255, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course', models.AutoField(primary_key=True, serialize=False, verbose_name='课程编号')),
                ('course_name', models.CharField(max_length=255, verbose_name='课程名称')),
                ('course_credits', models.IntegerField(verbose_name='学分')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('departments', models.AutoField(primary_key=True, serialize=False, verbose_name='院系')),
                ('departments_name', models.CharField(max_length=64, verbose_name='院系名称')),
            ],
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='超级管理员')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student', models.AutoField(primary_key=True, serialize=False, verbose_name='学号')),
                ('student_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('student_gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('student_time', models.DateField(verbose_name='出生年月')),
                ('student_class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.class', verbose_name='班级')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher', models.AutoField(primary_key=True, serialize=False, verbose_name='职工号')),
                ('teacher_name', models.CharField(max_length=64, verbose_name='姓名')),
                ('teacher_gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('teacher_time', models.DateField(verbose_name='出生年月')),
                ('teacher_phone', models.IntegerField(max_length=64, verbose_name='联系电话')),
                ('teacher_departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments', verbose_name='院系')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator_Login',
            fields=[
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.administrator', verbose_name='管理员ID')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Students_Login',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.students', verbose_name='学号')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Login',
            fields=[
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.teacher', verbose_name='职工号')),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional', models.AutoField(primary_key=True, serialize=False, verbose_name='专业ID')),
                ('professional_name', models.CharField(max_length=255, verbose_name='专业名称')),
                ('administrator_departments', models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='api.departments', verbose_name='院系')),
            ],
        ),
        migrations.CreateModel(
            name='Electives',
            fields=[
                ('electives', models.AutoField(primary_key=True, serialize=False, verbose_name='选修ID')),
                ('course_results', models.IntegerField(default=0, max_length=12, verbose_name='成绩')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses', verbose_name='课程编号')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.students', verbose_name='学号')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='course_departments',
            field=models.ForeignKey(default=1001, on_delete=django.db.models.deletion.CASCADE, to='api.departments', verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='class',
            name='professional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.professional', verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='administrator_departments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departments', verbose_name='院系'),
        ),
    ]
