# Generated by Django 4.1.2 on 2022-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='学号'),
        ),
    ]
