# Generated by Django 4.1.2 on 2022-11-30 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher', verbose_name='职工号')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses', verbose_name='课程编号')),
            ],
        ),
    ]
