# Generated by Django 4.1.2 on 2022-12-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teaching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_login',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher_login',
            name='teacher',
        ),
        migrations.AddField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Administrator_Login',
        ),
        migrations.DeleteModel(
            name='Students_Login',
        ),
        migrations.DeleteModel(
            name='Teacher_Login',
        ),
    ]
