# Generated by Django 4.1.2 on 2022-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_administrator_mail_students_mail_teacher_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='职工号'),
        ),
    ]
