# Generated by Django 4.1.2 on 2022-12-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_teacher_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher',
            new_name='teacherid',
        ),
    ]
