# Generated by Django 4.1.2 on 2022-12-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_teacher_teacher_teacherid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacherid',
            new_name='teacher',
        ),
    ]
