# Generated by Django 4.1.2 on 2022-12-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_teaching_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.class', verbose_name='班级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses', verbose_name='课程')),
            ],
        ),
    ]
