# Generated by Django 4.1.2 on 2022-12-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_class_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_choose',
            field=models.SmallIntegerField(choices=[(1, '选修'), (2, '必修')], default=1, verbose_name='选修/必修'),
            preserve_default=False,
        ),
    ]
