# Generated by Django 4.1.2 on 2022-12-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_course_selection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_selection',
            name='Course',
        ),
        migrations.AddField(
            model_name='course_selection',
            name='course',
            field=models.SmallIntegerField(choices=[(1, '开放选课'), (2, '关闭选课')], default=2, verbose_name='是否开放选课'),
        ),
    ]
