# Generated by Django 4.1.2 on 2022-12-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_students_login_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='students',
            name='mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mail',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
