# Generated by Django 4.1.2 on 2022-12-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_teacherid_teacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher', verbose_name='教师'),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courses', verbose_name='课程'),
        ),
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('teacher', 'course')},
        ),
    ]
