# Generated by Django 4.1.2 on 2022-12-08 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_teaching_course_alter_teaching_teacher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together=set(),
        ),
    ]
